// <auto-generated />
using Exam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exam.Migrations
{
    [DbContext(typeof(dataContext))]
    [Migration("20230220123614_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<string>("CategorieCategoryID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductsProductID")
                        .HasColumnType("TEXT");

                    b.HasKey("CategorieCategoryID", "ProductsProductID");

                    b.HasIndex("ProductsProductID");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Exam.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "SK1",
                            CategoryName = "Mobile Phone",
                            Description = "The Phone for every one",
                            Picture = "image1.jpg"
                        },
                        new
                        {
                            CategoryID = "SK2",
                            CategoryName = "Book",
                            Description = "Book for Student",
                            Picture = "image2.jpg"
                        });
                });

            modelBuilder.Entity("Exam.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryID")
                        .HasColumnType("TEXT");

                    b.Property<double>("Discontinued")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<double>("QuantityPerUnit")
                        .HasColumnType("REAL");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierID")
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitslnStock")
                        .HasColumnType("REAL");

                    b.Property<double>("UnnitsOnOrder")
                        .HasColumnType("REAL");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = "QW1",
                            CategoryID = "SK1",
                            Discontinued = 5.5999999999999996,
                            ProductName = "Iphone 15",
                            QuantityPerUnit = 1.0,
                            ReorderLevel = 1,
                            SupplierID = "HJ2",
                            UnitPrice = 23.440000000000001,
                            UnitslnStock = 0.13,
                            UnnitsOnOrder = 3.0
                        },
                        new
                        {
                            ProductID = "QW2",
                            CategoryID = "SK2",
                            Discontinued = 5.5999999999999996,
                            ProductName = "JAVA book",
                            QuantityPerUnit = 2.0,
                            ReorderLevel = 1,
                            SupplierID = "HJ3",
                            UnitPrice = 20.440000000000001,
                            UnitslnStock = 0.13,
                            UnnitsOnOrder = 3.0
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Exam.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategorieCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
